# Seven things an HTTP library/router should do in 2019
# -----------------------------------------------------

### 1. A simple "Hello World" sort of endpoint

GET http://localhost:3000/
Accept: application/json

### 2a. parse path params and emit JSON

GET http://localhost:3000/api/hello/Abe/Weissman
Accept: application/json

### 2c. parse JSON request body

POST http://localhost:3000/api/hello
Accept: application/json
Content-Type: application/json

{
  "first_name": "Midge",
  "last_name": "Maisel"
}


### 4a. JSON -> struct & update API
# Successive requests should update a shared counter

GET http://localhost:3000/counts/a
Accept: application/json

### 4b. JSON -> struct & update API
# Successive requests should update a shared counter

GET http://localhost:3000/counts/b
Accept: application/json

### 5. router decomposition; e.g. /api/ and /pages served by separate functions/impls

### 6. use a (global) state thing

### 7. middleware